spring.application.name=TestPaymentService

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

mybatis.configuration.map-underscore-to-camel-case=true

mybatis.configuration.default-enum-type-handler=org.apache.ibatis.type.EnumTypeHandler

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver